const{ GoogleGenAI } = require("@google/genai");
const {z} = require("zod")
const puppeteer = require("puppeteer")


const ai = new GoogleGenAI({
    apiKey: process.env.GENAI_API_KEY
});

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 to 100 indicating how well the candidate's profile matches the job description"),
    technicalQuestions: z.array(z.object({
    question: z.string().describe("The technical question that can be asked in the interview"),
    intention: z.string().describe("The interviewer's intention behind asking this question"),
    answer: z.string().describe("How the candidate should answer this question, including important points to cover")
})),

behaviouralQuestions: z.array(z.object({
    question: z.string().describe("The behavioural question that can be asked in the interview"),
    intention: z.string().describe("The interviewer's intention behind asking this question"),
    answer: z.string().describe("How the candidate should answer this question, including important points to cover")
})),
   skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which candidate is lacking"),
        severity: z.enum(["low","medium","high"]).describe("The severity of skill gap ")
            })).describe("List of skill gaps in the candidate's profile along with their severity"),
            preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in preparation plan ,starting from 1"),
        focus: z.string().describe("The main focus of the day in preparation plan e.g data structures,system designs ,mock interview "),
        tasks: z.array(z.string()).describe("List of the tasks to be done on this day to follow the preparation plan e.g read a specific book or work to do")
            })).describe("A day wise preparational plan for the candiate to follow in order to preapare for interview effectively"),
            title:z.string().describe("The title for the job for which job is generated")
})

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


    const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}
`

   const schema = z.toJSONSchema(interviewReportSchema);

console.log("SCHEMA BEING SENT:");
console.log(JSON.stringify(schema, null, 2));

const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
        responseMimeType: "application/json",
        responseJsonSchema: schema,
    }
});

    return JSON.parse(response.text)


}

async function genratePdfFromHtml(htmlContent){
    const browser = await puppeteer.launch({
    headless: true,
    args: ["--no-sandbox", "--disable-setuid-sandbox"]
})
    const page = await browser.newPage()
    await page.setContent(htmlContent, {waitUntil:"networkidle0"})

    const pdfBuffer = await page.pdf({format:"A4" , margin :{
          top: "20mm",
            bottom: "20mm",
            left: "15mm",
            right: "15mm"
    }
    }) 

    await browser.close()

    return pdfBuffer
}

async function generateResumePdf ({jobDescription,selfDescription,resume}){

    const resumePdfSchema = z.object({
        html: z.string().describe("the HTML content of the resume which can be converted into pdf using puppeteer")
    })

      const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `

    const response = await ai.models.generateContent({
        model:"gemini-3-flash-preview",
        contents:prompt,
       config:{
    responseMimeType: "application/json",
    responseJsonSchema: z.toJSONSchema(resumePdfSchema)
}
    })

    console.log(response.text)
  const jsonContent =  JSON.parse(response.text)

  const pdfBuffer = await genratePdfFromHtml(jsonContent.html)

  return pdfBuffer
}

module.exports = {generateInterviewReport,generateResumePdf}